# Generated by Django 5.0.6 on 2024-05-20 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_carrito_itemcarrito_carrito_productos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemcarrito',
            name='carrito',
        ),
        migrations.RemoveField(
            model_name='itemcarrito',
            name='producto',
        ),
        migrations.DeleteModel(
            name='Carrito',
        ),
        migrations.DeleteModel(
            name='ItemCarrito',
        ),
    ]
