# Generated by Django 5.0.6 on 2024-06-29 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_transferencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferencia',
            name='rut',
            field=models.CharField(default='1', max_length=20),
        ),
    ]
