# Generated by Django 5.0.6 on 2024-06-29 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_transferencia_rut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transferencia',
            name='codigoP',
            field=models.CharField(db_column='Codigo Producto', max_length=50),
        ),
    ]
